### ISSUE TITLE
部署错误，并且登录时候提示用户名不存在

### ISSUE THREAD

**Issue by hangxtx** [megagao/production_ms#2]
1：在部署过程中有错误：org.springframework.core.convert.ConversionFailedException: Failed to convert from type java.util.ArrayList<?> to type java.util.List<org.springframework.core.io.Resource> for value '[/WEB-INF/css/]'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.util.ArrayList<?> to type org.springframework.core.io.Resource
2：登录过程中：提示用户名不存在。使用的是数据表sys_user中的用户名和密码

**Comment by megagao** [comment]
@hangxtx 1、这个问题不影响正常部署；2、你用的是username和password两个字段登录的吗？试试登录名22  密码22

**Comment by hangxtx** [comment]
1.这个我在网上看到了解决办法，是命名冲突，将springmvc-servlet.xml中的bean id="conversionService"改为bean id="conversionService1"
2.我用的是这两个字段登录的，页面提示用户名不存在，控制台报错是org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): org.hqu.production_ms.mapper.authority.SysUserMapper.selectByExample。

**Comment by megagao** [comment]
@hangxtx 我这边又运行了一下，没发现类似的错误，SysUserMapper是mybatis逆向工程生成的，里面应该有selectByExample，你可以看看相对应的文件

**Comment by hangxtx** [comment]
恩恩，我的问题解决了，用的IDEA来导入的工程，没有在resource目录下生成对应的mapper XML文件，只有java目录下面有，手工增加目录及文件之后就成功部署了。谢谢分享啊！
